In [1]:
import pandas as pd

df_lucro_ano = pd.read_csv("../data/processed/lucro_liquido_2021_2025.csv")
df_pl_ano = pd.read_csv("../data/processed/patrimonio_liquido_2021_2025.csv")

df_roe = df_lucro_ano.merge(df_pl_ano, on=["DENOM_CIA", "ANO_ARQUIVO"], suffixes=("_LUCRO", "_PL"))
df_roe["ROE"] = df_roe["VL_CONTA_LUCRO"] / df_roe["VL_CONTA_PL"]

df_roe.sort_values("ROE", ascending=False).head(10)

,DENOM_CIA,SETOR_ATIV,ANO_ARQUIVO,VL_CONTA_LUCRO,VL_CONTA_REAIS,VL_CONTA_BI,VL_CONTA_PL,ROE
187,BRAZILIAN FINANCE E REAL ESTATE S.A.,Emp. Adm. Part. - Crédito Imobiliário,2021,12287.0,1.228700e+07,0.012287,0.0,inf
1201,RIO PARANAPANEMA ENERGIA S.A.,Energia Elétrica,2023,341617.0,3.416170e+08,0.341617,0.0,inf
1787,CLI SUL S.A.,Serviços Transporte e Logística,2024,57107.0,5.710700e+07,0.057107,0.0,inf
2132,B100 S.A.,Intermediação Financeira,2025,-465085.0,-4.650850e+08,-0.465085,-746.0,623.438338
682,MANGELS INDUSTRIAL S.A.,Emp. Adm. Part. - Metalurgia e Siderurgia,2022,258724.0,2.587240e+08,0.258724,7225.0,35.809550
1819,KARSTEN S.A.,Têxtil e Vestuário,2024,118409.0,1.184090e+08,0.118409,5469.0,21.650942
1471,INFRACOMMERCE CXAAS S.A.,Comércio (Atacado e Varejo),2024,-1756143.0,-1.756143e+09,-1.756143,-104790.0,16.758689
1579,ASA BRANCA HOLDING S.A.,Emp. Adm. Part. - Energia Elétrica,2024,-38290.0,-3.829000e+07,-0.038290,-2452.0,15.615824
429,OI S.A. - EM RECUPERAÇÃO JUDICIAL,Telecomunicações,2021,-8492526.0,-8.492526e+09,-8.492526,-722981.0,11.746541
2027,TERP GLBL BRASIL I PARTICIPAÇÕES S.A.,Emp. Adm. Part. - Energia Elétrica,2025,66065.0,6.606500e+07,0.066065,7938.0,8.322625

In [2]:
df_roe[df_roe["VL_CONTA_PL"] == 0][["DENOM_CIA", "ANO_ARQUIVO", "VL_CONTA_LUCRO", "VL_CONTA_PL"]]
#Aqui deu um probleminha porque algumas empresas não tinham patrimônio líquido, então o ROE deu infinito. Então vamos filtrar essas empresas para ver o que aconteceu.

,DENOM_CIA,ANO_ARQUIVO,VL_CONTA_LUCRO,VL_CONTA_PL
187,BRAZILIAN FINANCE E REAL ESTATE S.A.,2021,12287.0,0.0
509,CLARANET TECHNOLOGY S.A.,2022,-14716.0,0.0
666,CIA CELG DE PARTICIPACOES - CELGPAR,2022,0.0,0.0
1121,CIA CELG DE PARTICIPACOES - CELGPAR,2023,0.0,0.0
1201,RIO PARANAPANEMA ENERGIA S.A.,2023,341617.0,0.0
1664,RIO PARANAPANEMA ENERGIA S.A.,2024,0.0,0.0
1787,CLI SUL S.A.,2024,57107.0,0.0
1807,TIM S.A.,2024,0.0,0.0
2108,RIO PARANAPANEMA ENERGIA S.A.,2025,0.0,0.0
2230,CLI SUL S.A.,2025,0.0,0.0
2243,TIM S.A.,2025,0.0,0.0

In [3]:
# remove linhas com PL zerado (dado incompleto/inconsistente da fonte)
antes = len(df_roe)
df_roe = df_roe[df_roe["VL_CONTA_PL"] != 0].copy()
depois = len(df_roe)
print(f"Removidas {antes - depois} linhas com PL zerado (dado inconsistente da CVM)")

Removidas 11 linhas com PL zerado (dado inconsistente da CVM)

In [4]:
df_roe[df_roe["ROE"] < 0][["DENOM_CIA", "ANO_ARQUIVO", "VL_CONTA_LUCRO", "VL_CONTA_PL", "ROE"]].sort_values("ROE")

,DENOM_CIA,ANO_ARQUIVO,VL_CONTA_LUCRO,VL_CONTA_PL,ROE
1008,MARISA LOJAS S.A.,2023,-520753.000,4.670000e+02,-1115.102784
1589,MANGELS INDUSTRIAL S.A.,2024,-41575.000,5.530000e+02,-75.180832
148,ALPHAVILLE S.A.,2021,-381698.000,1.279600e+04,-29.829478
1402,MINERVA S.A.,2024,-1563806.000,8.721700e+04,-17.930060
1054,VIVER INCORPORADORA E CONSTRUTORA S.A.,2023,-72749.000,5.293000e+03,-13.744379
...,...,...,...,...,...
1883,MÉLIUZ S.A.,2025,-1140.000,5.180950e+05,-0.002200
668,SERENA ENERGIA S.A.,2022,-8031.000,5.171274e+06,-0.001553
1524,SER EDUCACIONAL S.A.,2024,-1162.000,1.208464e+06,-0.000962
542,CIA BRASILEIRA DE DISTRIBUICAO,2022,-4000.000,1.373300e+07,-0.000291
1612,YBYRÁ CAPITAL S.A.,2024,-49.973,4.662467e+06,-0.000011

In [5]:
LIMITE_PL_MINIMO = 10_000_000  # ajuste esse valor conforme necessário

df_roe_filtrado = df_roe[df_roe["VL_CONTA_PL"].abs() >= LIMITE_PL_MINIMO].copy()

print(f"Removidas {len(df_roe) - len(df_roe_filtrado)} linhas com PL abaixo do limite de materialidade")
df_roe_filtrado.sort_values("ROE", ascending=False).head(10)

Removidas 1908 linhas com PL abaixo do limite de materialidade

,DENOM_CIA,SETOR_ATIV,ANO_ARQUIVO,VL_CONTA_LUCRO,VL_CONTA_REAIS,VL_CONTA_BI,VL_CONTA_PL,ROE
892,OI S.A. - EM RECUPERAÇÃO JUDICIAL,Telecomunicações,2022,-19265934.0,-1.926593e+10,-19.265934,-21846002.0,0.881897
2053,BB SEGURIDADE PARTICIPAÇÕES S.A.,Emp. Adm. Part. - Seguradoras e Corretoras,2025,9017329.0,9.017329e+09,9.017329,10384393.0,0.868354
817,SUZANO S.A.,Papel e Celulose,2022,23394887.0,2.339489e+10,23.394887,33166365.0,0.705380
688,SUZANO HOLDING S.A.,Emp. Adm. Part. - Papel e Celulose,2022,23392406.0,2.339241e+10,23.392406,33239904.0,0.703745
2249,OI S.A. - EM RECUPERAÇÃO JUDICIAL,Telecomunicações,2025,-36368915.0,-3.636892e+10,-36.368915,-52689960.0,0.690244
2176,BRASKEM S.A.,Petroquímicos e Borracha,2025,-10961000.0,-1.096100e+10,-10.961000,-16502000.0,0.664223
307,VALE S.A.,Extração Mineral,2021,121343000.0,1.213430e+11,121.343000,197058000.0,0.615773
326,CIA SIDERURGICA NACIONAL,Metalurgia e Siderurgia,2021,13595621.0,1.359562e+10,13.595621,23374389.0,0.581646
359,SUZANO S.A.,Papel e Celulose,2021,8635532.0,8.635532e+09,8.635532,15175130.0,0.569058
227,SUZANO HOLDING S.A.,Emp. Adm. Part. - Papel e Celulose,2021,8634583.0,8.634583e+09,8.634583,15230792.0,0.566916

In [6]:
#Antes de importar, vamos mostrar uma coluna nova mostrando quando VL_CONTA_PL é negativo, para ver se tem alguma empresa com patrimônio líquido negativo. Se tiver, o ROE é enganoso.
df_roe_filtrado["ROE_ENGANOSO"] = df_roe_filtrado["VL_CONTA_PL"] < 0
df_roe_filtrado.to_csv("../data/processed/roe_2021_2025.csv", index=False)