In [4]:
import pandas as pd
import numpy as np
import sqlite3

df_roe= pd.read_csv("../data/processed/roe_2021_2025.csv")

sql = sqlite3.connect("../data/processed/empresa_b3.db")
df_roe.to_sql("roe", sql, if_exists="replace", index=False)

384

In [ ]:
teste = pd.read_sql("Select * from roe", sql)
teste
#SQL Checkp

,DENOM_CIA,SETOR_ATIV,ANO_ARQUIVO,VL_CONTA_LUCRO,VL_CONTA_REAIS,VL_CONTA_BI,VL_CONTA_PL,ROE,ROE_ENGANOSO
0,COSAN S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,14519180.0,1.451918e+10,14.519180,28870022.0,0.502915,0
1,JBS S.A.,Alimentos,2021,25184602.0,2.518460e+10,25.184602,47796720.0,0.526911,0
2,BCO BRADESCO S.A.,Bancos,2021,39414765.0,3.941476e+10,39.414765,150228707.0,0.262365,0
3,BCO BRASIL S.A.,Bancos,2021,33015754.0,3.301575e+10,33.015754,146110233.0,0.225965,0
4,BCO SANTANDER (BRASIL) S.A.,Bancos,2021,29010076.0,2.901008e+10,29.010076,105974495.0,0.273746,0
...,...,...,...,...,...,...,...,...,...
379,LOCALIZA RENT A CAR S.A.,Serviços Transporte e Logística,2025,7367560.0,7.367560e+09,7.367560,25539012.0,0.288483,0
380,TELEFÔNICA BRASIL S.A,Telecomunicações,2025,11734875.0,1.173488e+10,11.734875,69002726.0,0.170064,0
381,TIM BRASIL SERVIÇOS E PARTICIPAÇÕES S.A.,Telecomunicações,2025,5800850.0,5.800850e+09,5.800850,19545484.0,0.296787,0
382,V. TAL - REDE NEUTRA DE TELECOMUNICAÇÕES S.A.,Telecomunicações,2025,-12991140.0,-1.299114e+10,-12.991140,16459637.0,-0.789273,0
383,PETTENATI S.A. INDUSTRIA TEXTIL,Têxtil e Vestuário,2025,91740345.0,9.174034e+10,91.740345,510135052.0,0.179835,0

In [7]:
query = """
SELECT 
    DENOM_CIA,
    AVG(ROE) as ROE_MEDIO,
    COUNT(*) as QTD_ANOS
FROM roe
WHERE ROE_ENGANOSO = 0
GROUP BY DENOM_CIA
HAVING COUNT(*) >= 3
ORDER BY ROE_MEDIO DESC
LIMIT 10
"""
# Ou poderiamos escrever assim: query = "SELECT DENOM_CIA, AVG(ROE) as ROE_MEDIO, COUNT(*) as QTD_ANOS FROM roe WHERE ROE_ENGANOSO = 0 GROUP BY DENOM_CIA HAVING COUNT(*) >= 3 ORDER BY ROE_MEDIO DESC LIMIT 10"

top10_sql = pd.read_sql(query, sql)
top10_sql

                            DENOM_CIA  ROE_MEDIO  QTD_ANOS
0                           VALE S.A.   1.242011         5
1  PETROLEO BRASILEIRO S.A. PETROBRAS   1.088362         5
2                   CPFL ENERGIA S.A.   1.051735         5
3     B3 S.A. - BRASIL, BOLSA, BALCÃO   0.898803         5
4                   VIBRA ENERGIA S/A   0.875672         5
5                  CSN MINERAÇÃO S.A.   0.739738         4
6             METALURGICA GERDAU S.A.   0.675172         5
7                  ISA ENERGIA BRASIL   0.661977         5
8                          AMBEV S.A.   0.660466         5
9                         ITAÚSA S.A.   0.647660         5

In [13]:
Top_lucros = """
SELECT
    DENOM_CIA,
    SUM(VL_CONTA_REAIS) as LUCRO_TOTAL
FROM roe
GROUP BY DENOM_CIA
ORDER BY LUCRO_TOTAL DESC
LIMIT 10
"""

top10_lucros = pd.read_sql(Top_lucros, sql)
top10_lucros

                            DENOM_CIA   LUCRO_TOTAL
0           VIVARA PARTICIPAÇÕES S.A.  4.130141e+12
1  PETROLEO BRASILEIRO S.A. PETROBRAS  2.067478e+12
2                           VALE S.A.  1.228088e+12
3   METISA METALURGICA TIMBOENSE S.A.  6.247358e+11
4     PETTENATI S.A. INDUSTRIA TEXTIL  5.783385e+11
5                          AMBEV S.A.  2.867258e+11
6                         ITAÚSA S.A.  2.730280e+11
7                     BCO BRASIL S.A.  2.540454e+11
8                   BCO BRADESCO S.A.  1.934840e+11
9               QUALITY SOFTWARE S.A.  1.735763e+11

,DENOM_CIA,SETOR_ATIV,ANO_ARQUIVO,VL_CONTA_LUCRO,VL_CONTA_REAIS,VL_CONTA_BI,VL_CONTA_PL,ROE,ROE_ENGANOSO
0,COSAN S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,14519180.0,1.451918e+10,14.519180,28870022.0,0.502915,False
1,JBS S.A.,Alimentos,2021,25184602.0,2.518460e+10,25.184602,47796720.0,0.526911,False
2,BCO BRADESCO S.A.,Bancos,2021,39414765.0,3.941476e+10,39.414765,150228707.0,0.262365,False
3,BCO BRASIL S.A.,Bancos,2021,33015754.0,3.301575e+10,33.015754,146110233.0,0.225965,False
4,BCO SANTANDER (BRASIL) S.A.,Bancos,2021,29010076.0,2.901008e+10,29.010076,105974495.0,0.273746,False
...,...,...,...,...,...,...,...,...,...
379,LOCALIZA RENT A CAR S.A.,Serviços Transporte e Logística,2025,7367560.0,7.367560e+09,7.367560,25539012.0,0.288483,False
380,TELEFÔNICA BRASIL S.A,Telecomunicações,2025,11734875.0,1.173488e+10,11.734875,69002726.0,0.170064,False
381,TIM BRASIL SERVIÇOS E PARTICIPAÇÕES S.A.,Telecomunicações,2025,5800850.0,5.800850e+09,5.800850,19545484.0,0.296787,False
382,V. TAL - REDE NEUTRA DE TELECOMUNICAÇÕES S.A.,Telecomunicações,2025,-12991140.0,-1.299114e+10,-12.991140,16459637.0,-0.789273,False
383,PETTENATI S.A. INDUSTRIA TEXTIL,Têxtil e Vestuário,2025,91740345.0,9.174034e+10,91.740345,510135052.0,0.179835,False