In [1]:
import sqlite3

import pandas as pd

df_roe= pd.read_csv("../data/processed/roe_2021_2025.csv")

sql = sqlite3.connect("../data/processed/empresa_b3.db")
df_roe.to_sql("roe", sql, if_exists="replace", index=False)

347

In [2]:
teste = pd.read_sql("Select * from roe", sql)
teste
#SQL Checkp

,DENOM_CIA,SETOR_ATIV,ANO_ARQUIVO,VL_CONTA_LUCRO,VL_CONTA_REAIS,VL_CONTA_BI,VL_CONTA_PL,ROE,ROE_ENGANOSO
0,COSAN S.A.,"Agricultura (Açúcar, Álcool e Cana)",2021,6350776.0,6.350776e+09,6.350776,28870022.0,0.219978,0
1,JBS S.A.,Alimentos,2021,20529653.0,2.052965e+10,20.529653,47796720.0,0.429520,0
2,BCO BRADESCO S.A.,Bancos,2021,23380804.0,2.338080e+10,23.380804,150228707.0,0.155635,0
3,BCO BRASIL S.A.,Bancos,2021,19722871.0,1.972287e+10,19.722871,146110233.0,0.134986,0
4,BCO SANTANDER (BRASIL) S.A.,Bancos,2021,15559323.0,1.555932e+10,15.559323,105974495.0,0.146821,0
...,...,...,...,...,...,...,...,...,...
342,HAPVIDA PARTICIPAÇÕES E INVESTIMENTOS S.A.,Serviços Médicos,2025,-142169.0,-1.421690e+08,-0.142169,48250270.0,-0.002946,0
343,LOCALIZA RENT A CAR S.A.,Serviços Transporte e Logística,2025,1870470.0,1.870470e+09,1.870470,25539012.0,0.073240,0
344,TELEFÔNICA BRASIL S.A,Telecomunicações,2025,6177543.0,6.177543e+09,6.177543,69002726.0,0.089526,0
345,TIM BRASIL SERVIÇOS E PARTICIPAÇÕES S.A.,Telecomunicações,2025,3401422.0,3.401422e+09,3.401422,19545484.0,0.174026,0
346,V. TAL - REDE NEUTRA DE TELECOMUNICAÇÕES S.A.,Telecomunicações,2025,-13855499.0,-1.385550e+10,-13.855499,16459637.0,-0.841786,0

In [3]:
query = """
SELECT 
    DENOM_CIA,
    AVG(ROE) as ROE_MEDIO,
    COUNT(*) as QTD_ANOS
FROM roe
WHERE ROE_ENGANOSO = 0
GROUP BY DENOM_CIA
HAVING COUNT(*) >= 3
ORDER BY ROE_MEDIO DESC
LIMIT 10
"""
# Ou poderiamos escrever assim: query = "SELECT DENOM_CIA, AVG(ROE) as ROE_MEDIO, COUNT(*) as QTD_ANOS FROM roe WHERE ROE_ENGANOSO = 0 GROUP BY DENOM_CIA HAVING COUNT(*) >= 3 ORDER BY ROE_MEDIO DESC LIMIT 10"

top10_sql = pd.read_sql(query, sql)
top10_sql

                             DENOM_CIA  ROE_MEDIO  QTD_ANOS
0                   CSN MINERAÇÃO S.A.   0.372136         4
1                  SUZANO HOLDING S.A.   0.336224         5
2                          SUZANO S.A.   0.335530         5
3                            VALE S.A.   0.303893         5
4                             WEG S.A.   0.301671         5
5   PETROLEO BRASILEIRO S.A. PETROBRAS   0.297393         5
6                            PRIO S.A.   0.285982         3
7                    CPFL ENERGIA S.A.   0.274379         5
8  CAIXA SEGURIDADE PARTICIPAÇÕES S.A.   0.268841         5
9                          KLABIN S.A.   0.243068         3

In [4]:
Top_lucros = """
SELECT
    DENOM_CIA,
    SUM(VL_CONTA_REAIS) as LUCRO_TOTAL
FROM roe
GROUP BY DENOM_CIA
ORDER BY LUCRO_TOTAL DESC
LIMIT 10
"""

top10_lucros = pd.read_sql(Top_lucros, sql)
top10_lucros

                            DENOM_CIA   LUCRO_TOTAL
0  PETROLEO BRASILEIRO S.A. PETROBRAS  5.690490e+11
1                           VALE S.A.  3.004760e+11
2                     BCO BRASIL S.A.  1.286913e+11
3                   BCO BRADESCO S.A.  1.005676e+11
4                          AMBEV S.A.  7.380972e+10
5                         ITAÚSA S.A.  7.286000e+10
6         BCO SANTANDER (BRASIL) S.A.  6.577650e+10
7                            JBS S.A.  5.924167e+10
8                         SUZANO S.A.  5.252978e+10
9                 SUZANO HOLDING S.A.  5.244705e+10